# This file was *autogenerated* from the file 3-tour.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10)
sage: from abelfunctions import *  # import all functionality
sage: R.<x,y> = QQ[]
sage: f = x**_sage_const_2 *y**_sage_const_3  - x**_sage_const_4  + _sage_const_1 
sage: X = RiemannSurface(f); X  # create a Riemann surface
Riemann surface defined by f = x**_sage_const_7  - _sage_const_2 *x**_sage_const_3 *y + y**_sage_const_3 
sage: g = X.genus(); g
_sage_const_4 
sage: for n in range(_sage_const_10 ): print n
